# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4
trigger:
- main
pool:
  vmImage: 'ubuntu-latest'
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  
stages:
  - stage: Build
    jobs:
    - job: Build
      pool:
        vmImage: 'ubuntu-latest'
      displayName: 'Build job'
      steps:
        # The first task is the dotnet command build, pointing to our csproj file
        - task: UseDotNet@2
          inputs:
            version: 6.0.x
        - task: DotNetCoreCLI@2
          inputs:
            command: 'restore'
            projects: '$(solution)'
            feedsToUse: config
            nugetConfigPath: '$(System.DefaultWorkingDirectory)/Demo/Nuget.config'
          displayName: 'dotnet restore $(buildConfiguration)'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            arguments: '--configuration $(buildConfiguration)'
            projects: '$(solution)'
          displayName: 'dotnet build $(buildConfiguration)'
        
        - task: PublishBuildArtifacts@1
          inputs:
            pathToPublish: '$(System.DefaultWorkingDirectory)'
            artifactName: drop